services:
  - redis-server
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7-dev"  # need to investigate the failure
  - "pypy"
#  - "pypy3"
install:
  - make develop
script:
  - travis_wait make test
after_success:
  - pip install -q python-coveralls
  - coveralls
